// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBpvDmuLm008QLogmHys3KMAc5Q9QIsrns',
    appId: '1:1079035941759:web:44fd85e64e36da18b4804a',
    messagingSenderId: '1079035941759',
    projectId: 'flutter-notifications-2b786',
    authDomain: 'flutter-notifications-2b786.firebaseapp.com',
    storageBucket: 'flutter-notifications-2b786.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFo26xxe0BbNLBWNvudPu43mDiEZHqHxo',
    appId: '1:1079035941759:android:a4f8572c9273581eb4804a',
    messagingSenderId: '1079035941759',
    projectId: 'flutter-notifications-2b786',
    storageBucket: 'flutter-notifications-2b786.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDVSxEOaTN6Je85H05Ges2ITbj2w0VXCV0',
    appId: '1:1079035941759:ios:4f700c06312dfcfeb4804a',
    messagingSenderId: '1079035941759',
    projectId: 'flutter-notifications-2b786',
    storageBucket: 'flutter-notifications-2b786.appspot.com',
    androidClientId: '1079035941759-dri9r3sridv29da3e8q09qh7knrjpaen.apps.googleusercontent.com',
    iosBundleId: 'com.example.pushApp',
  );
}
